### PR TITLE
PCM-7359: fixed conditional attach file button from being enabled when not allowed

### PR DESCRIPTION
**Pull request by jeudy100**

### CODE REVIEW

**Comment by vrathee** [comment]
@jeudy100  Some tests are failing here.. please have a look at it..

**Comment by anujsi** [comment]
Remove console.log from the test file.

**Comment by anujsi** [comment]
console.log(mockScope.addFile);

**Comment by gandhikeyur** [comment]
Please remove console log in another PR, merging this now to pass the fixes to the QA team for testing.

**Pull request merged**
