### PR TITLE
Pcm 6613 - Authorization is not added in the feedback API .

### PR DESCRIPTION
**Pull request by anujsi**
@engineersamuel  @kunyan  @gandhikeyur  @aksgupta14  Please review.
https://projects.engineering.redhat.com/browse/PCM-6613

### CODE REVIEW

**Comment by gakshat14** [comment]
Reviewed!

**Comment by engineersamuel** [comment]
I really wish we could avoid including a forked hydrajs in the actual codebase, but it is what it is is for now I guess.

**Comment by anujsi** [comment]
@engineersamuel  we are not able to add hydrajs in the package.json file because we can not access hydrajs from gitlab .

**Comment by engineersamuel** [comment]
@anujsi  Oh I know, just saying, it's not optimal, but not much we can do about it right now.

**Pull request merged**
