### PR TITLE
PCM-7419: fixed canceling upload logic

### PR DESCRIPTION
**Pull request by jeudy100**
Blocked by:
1. [redhataccess/stratajs!59](https://github.com/redhataccess/stratajs/pull/59)
2. [hydrajs!295](https://gitlab.cee.redhat.com/redhataccess/hydrajs/merge_requests/295)

### CODE REVIEW

**Comment by anujsi** [comment]
Reviewed.

**Comment by vrathee** [comment]
Suggested some changes in hydrajs.. Thus, this needs to be retested after those changes..
The changes for PCM are Reviewed!

**Comment by jeudy100** [comment]
Retested the logic and everything looks good!

**Comment by vrathee** [comment]
@jeudy100 I guess this will also need version bump to stratajs..

**Comment by jeudy100** [comment]
@vrathee @gandhikeyur It turns out you cannot use lambda functions in stratajs and it was giving me an error when i ran npm run test. I made a mr https://github.com/redhataccess/stratajs/pull/60 for it.

**Comment by gandhikeyur** [comment]
@jeudy100 Please resolve merge conflicts and also update the strata js version in bower json.

**Comment by vrathee** [comment]
Reviewed!

**Pull request merged**
