### PR TITLE
PCM-8058: added asterisk to severity icon when it has RMEs

### PR DESCRIPTION
**Pull request by jeudy100**
@anujsi @vrathee please review

### CODE REVIEW

**Comment by vrathee** [comment]
Reviewed!

**Comment by praniredhat** [comment]
@jeudy100 Is the given solution `asterisk beside severity to represent this case is escalated` is approved by UX team ( @asonawan ) ?

Because to me this asterisk seems to have hidden meaning. How will user know what does it mean ?

**Comment by jeudy100** [comment]
@praniredhat I have not and you are right. I could put a tooltip around the icon that will bring up a message, but that could be a little much if there are a lot of "asterisked" cases. I could add another column called "Escalated" and it could be just a checkmark to keep the column small (@asonawan)?

**Comment by vrathee** [comment]
@jeudy100 I have commented on the JIRA to get clarity on how it should look. Holding off the merge till then.

**Comment by jeudy100** [comment]
@vrathee @praniredhat I added the column and a tooltip. Inside the column you will either have a a check or an x. The tooltip is there because there are no column headers to explain what it actually is and just having a x or check could still be confusing as to what it defines. I know in the jira @vrathee you said to just leave it blank when there are no escalations, but I thought it would be confusing to  just have an empty column.

**Pull request merged**
