### PR TITLE
Update template pot

### PR DESCRIPTION
**Pull request by kunyan**
There has some texts need to run npm build first, then could generated to template.pot

### CODE REVIEW

**Comment by kunyan** [comment]
@gandhikeyur pls review, the UT has failed, but it shouldn't related with this change

**Comment by gandhikeyur** [comment]
As I would be on leave tomorrow, @vrathee Please review this and discuss about Unit tests with @kunyan 
If all looks good, please merge this PR.

**Comment by kunyan** [comment]
@vrathee pls review

**Comment by vrathee** [comment]
Reviewed!

**Pull request merged**
