### PR TITLE
Pcm 1116

### PR DESCRIPTION
**Pull request by sshumake**
@renujhamtani @pbathia @ardasgup @avijra first pass?

### CODE REVIEW

**Comment by ardasgup** [comment]
@sshumake looks good, i see u have created /redhataccess/redhat_access_angular_ui_common for the common components what about the scss files ? are you planning to have a separate entity for that too.
Oh and moving ascension part to gitLab is also good !

**Comment by renujhamtani** [comment]
Looks good!

**Comment by pbathia** [comment]
@sshumake I can't imagine myself checking PR with 133 files modified :) but it should be good if we are able to launch ascension and with basic smoke testing  :)

**Comment by sshumake** [comment]
@ardasgup  Yes I have a few passes for this code but I wanted to get the basic functionality live ASAP.

**Pull request merged**
