### PR TITLE
changes for pcm-922, as per latest email from Jeremy

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@sshumake @renujhamtani Please review and merge. This is dependent on 
https://projects.engineering.redhat.com/browse/CPSTRATA-377.

Please merge https://github.com/redhataccess/stratajs/pull/17 and https://github.com/redhataccess/redhat_access_angular_ui_common/pull/5 before merging this PR.

**Comment by renujhamtani** [comment]
@sshumake  Please do not merge this unless the strata dependency is on QA else the create case will fail.

**Comment by renujhamtani** [comment]
@sshumake I think we should not merge this unless the strata code in in prod because if the strata code is on QA and we push this to QA...everything will look good on QA...but if we push to prod before strata, then create case will fail.

**Comment by sshumake** [comment]
@renujhamtani @pbathia  Agreed this should not be merged.  Also it appears the endpoint is being modfied[1]

https://projects.engineering.redhat.com/browse/CPSTRATA-377

**Comment by renujhamtani** [comment]
Closing and not merging this as i have created a new PR which would not have any merge conflicts.

**Pull request closed without merging**
