### PR TITLE
code changes for pcm-690

### PR DESCRIPTION
**Pull request by gandhikeyur**
@renujhamtani @ardasgup Please review changes for pcm 690.

### CODE REVIEW

**Comment by renujhamtani** [comment]
Looks good!

**Comment by renujhamtani** [comment]
@gandhikeyur Please correct the test cases. They are failing. After this, I will merge

**Comment by gandhikeyur** [comment]
@renujhamtani Edited test case for pcm 690.

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
