### PR TITLE
changes for pcm-902

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@ardasgup @renujhamtani Please review and merge

**Comment by renujhamtani** [comment]
Reviewed!

**Comment by pbathia** [comment]
@ardasgup Please review. I have kept the foreach loop as it is as performance is better than native for loop.
For assignment I have changed to only flag instead of full object.

**Comment by pbathia** [comment]
@renujhamtani  @ardasgup Reverted the changes, as it is not working when we just try to assign some property value when we are iterating the same object.

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
