### PR TITLE
PCM-943

### PR DESCRIPTION
**Pull request by jtrantin**
@renujhamtani @ardasgup Please review.

### CODE REVIEW

**Comment by renujhamtani** [comment]
@jtrantin  Please fix the unit test cases. To check this, you can run grunt test and fix it.

**Comment by ardasgup** [comment]
Reviewed! Looks good, Just the test fix required.

**Comment by jtrantin** [comment]
@ardasgup @renujhamtani Fixed the tests.

**Comment by ardasgup** [comment]
Reviewed!

**Comment by renujhamtani** [comment]
This may  break the automation test cases. I am merging this hoping the subtask PCM-1383 is resolved.

**Pull request merged**
