### PR TITLE
changes for pcm-867

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@sshumake @renujhamtani Please review and merge.
Until we get fix for https://projects.engineering.redhat.com/browse/UNIFIED-757, lets keep the sort order as default which is by collab score.

**Comment by renujhamtani** [comment]
Reviewed ! looks good!

**Comment by pbathia** [comment]
@ardasgup Please review.

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
