### PR TITLE
Fix for fts flag being checked for all sev1 sev2 cases

### PR DESCRIPTION
**Pull request by vrathee**
@anujsi Please Review

### CODE REVIEW

**Comment by anujsi** [comment]
Reviewed.

**Comment by gandhikeyur** [comment]
Reviewed

**Comment by vrathee** [comment]
@dvf1976 I do not have any particular objection to this change. My main intention in this PR was to make it simple enough for me to understand while keeping it as close as possible to how things were currently written :) . Didn't wanted to drastically change stuff in a hotfix.

I will create a JIRA and link this comment so that we can simplify this further.

**Comment by vrathee** [comment]
@dvf1976 Created https://projects.engineering.redhat.com/browse/PCM-7242 to incorporate the suggestions

**Pull request merged**
