### PR TITLE
changes for pcm-574,

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@renujhamtani @sshumake Please review and merge. There is still one known issue in this which is blocked by UDS. I have updated JIRA accordingly.

**Comment by pbathia** [comment]
@ardasgup Please review.
@sshumake  Review css changes whenever you get time, even though PR is merged.

**Comment by ardasgup** [comment]
Reviewed!

**Comment by renujhamtani** [comment]
Reviewed! Merging!

**Pull request merged**
