### PR TITLE
Pcm 389

### PR DESCRIPTION
**Pull request by sshumake**
@renujhamtani @ardasgup @avijra @gandhikeyur 

Look at that scss ninjaing!

### CODE REVIEW

**Comment by ardasgup** [comment]
@sshumake sorry but i have lost all my ninja powers, no clue what these changes would be doing :/ all look good :-)

**Comment by renujhamtani** [comment]
@sshumake These changes will have a good impact on automation testing. The automation also needs to be checked. I am sure this would fail many test cases.

**Comment by sshumake** [comment]
@renujhamtani @ardasgup @avijra @gandhikeyur  Did some fixes and merging.  This will most likely break regression automation.

**Comment by renujhamtani** [comment]
Looks good.

**Comment by renujhamtani** [comment]
@ardasgup @avijra @gandhikeyur Merging this. Please review even if this is merged.

**Comment by avijra** [comment]
looks fine!!

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
