### PR TITLE
first pass for showing bugzilla

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@sshumake @renujhamtani this is first pass for PCM-1071, still some information is not available like whether bug is primary or not from UDS. We can add that info once its available. Till this we can show atleast attached bugzilla as per new mockups. 

Please review and merge.

**Comment by renujhamtani** [comment]
Reviewed! Looks Good!

**Comment by renujhamtani** [comment]
@ardasgup Please review this.

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
