### PR TITLE
first draft for pcm-558

### PR DESCRIPTION
**Pull request by pbathia**

### CODE REVIEW

**Comment by pbathia** [comment]
@renujhamtani @sshumake please review and please take this task further.
I have commented and also added TODO where what logic needs to be put. If you guys have any doubts please feel free to give me a call.

**Comment by renujhamtani** [comment]
Looks good! Thanks Pranjal!

**Comment by renujhamtani** [comment]
@ardasgup Please review this.

**Comment by renujhamtani** [comment]
@ardasgup I am merging this change without incorporating ur comment as i would take up this work from Pranjal. To avoid merge conflicts, I am merging this and would open a new PR for the reamining changes + ur comment.

**Pull request merged**
