### PR TITLE
demo-fixes

### PR DESCRIPTION
**Pull request by sshumake**
This contains bugs needing fixes for the demo on Friday.  I will create Jiras to track tomorrow
-link to solutions fixed
-updating new user on ownership
-Fix searching for invalid case ID
-Suggestions pinning fixed
-solutions abstract now showing when searching
-pull discussion and history on case load

### CODE REVIEW

**Comment by sshumake** [comment]
@ardasgup @renujhamtani

**Comment by renujhamtani** [comment]
Reviewed!

**Comment by ardasgup** [comment]
Reviewed!

**Comment by ardasgup** [comment]
@renujhamtani  looks good !

**Comment by pbathia** [comment]
Looks good.

**Pull request merged**
