### PR TITLE
PCM-1400

### PR DESCRIPTION
**Pull request by jtrantin**
@renujhamtani @vrathee Please review.

### CODE REVIEW

**Comment by renujhamtani** [comment]
@ardasgup I think Aritro has a better context on this. Requesting him to review this as this is critical

**Comment by ardasgup** [comment]
@jtrantin So now that you have removed that onchange event from the severity selector, how is the FTS flag set now when a user changes severity to sev1 from sev3. Have you taken care that in the other method updateSeverity()  ?

**Comment by renujhamtani** [comment]
@jtrantin I am waiting for all unit test cases to be executed. Please contact dkoul or Swapna for this.

**Comment by jtrantin** [comment]
@renujhamtani @ardasgup I have fixed the 24x7 use case. Verified tests create_case and support_casegroup_attachment_submit from PCM-CUKES.

**Comment by renujhamtani** [comment]
@jtrantin I will merge this only after the prod push as these have many cases and deepak would be able to test this fully..

**Comment by renujhamtani** [comment]
Merging this and Deepak would test this in detail on Monday!

**Pull request merged**
