### PR TITLE
fix various spacing issues / pagination / update button class & styling

### PR DESCRIPTION
**Pull request by sshumake**
@mattnolting Is there a list of the issues that fixed(did this come from an etherpad)?  Id like something for test to verify.

@ardasgup @pbathia @renujhamtani - Please review.  I will merge when I get a Jira tracking the fixes.

### CODE REVIEW

**Comment by ardasgup** [comment]
Reviewed! @sshumake looking at the changes don't think there is anything which our tests can(should) cover.

**Comment by renujhamtani** [comment]
Looks good!

**Comment by pbathia** [comment]
Reviewed.

**Comment by renujhamtani** [comment]
@sshumake @pbathia @ardasgup There are many styling changes in this pull request which has broken automation. None of us remembered that:(

**Pull request merged**
