### PR TITLE
PCM-839 changes

### PR DESCRIPTION
**Pull request by renujhamtani**
@ardasgup @pbathia Please review.

### CODE REVIEW

**Comment by ardasgup** [comment]
Reviewed!

**Comment by pbathia** [comment]
@renujhamtani Dont you think we should use CaseService instead of this @ https://github.com/renujhamtani/redhat_access_angular_ui/blob/PCM-839/app/cases/controllers/new.js#L241

**Comment by renujhamtani** [comment]
@pbathia Incorporated your review comments. please review.

**Comment by pbathia** [comment]
Looks good

**Pull request merged**
