### PR TITLE
PCM-7600: Permanent links to comment anchors don't work beyond page 1.

### PR DESCRIPTION
**Pull request by chopraapooja**
Jira: https://projects.engineering.redhat.com/browse/PCM-7600  
Please review @anujsi @vrathee

### CODE REVIEW

**Comment by anujsi** [comment]
@chopraapooja you can use let instead of var
var sorted = orderBy(DiscussionService.discussionElements, "sortModifiedDate");

**Comment by anujsi** [comment]
Reviewed.

**Comment by vrathee** [comment]
Reviewed!

**Comment by chopraapooja** [comment]
test comment

**Pull request merged**
