### PR TITLE
PCM-556 changes

### PR DESCRIPTION
**Pull request by renujhamtani**
@gandhikeyur @vrathee Please review

### CODE REVIEW

**Comment by gandhikeyur** [comment]
@renujhamtani Not sure if the label should be "Checksum" or something like "SHA-256".

**Comment by renujhamtani** [comment]
@sshumake Do you have any say on the label?

**Comment by renujhamtani** [comment]
@gandhikeyur I talked with @sshumake and he agreed on having the title as "SHA-256" instead of checksum. I have pushed the changes. Please review again!

**Comment by renujhamtani** [comment]
Merging this!

**Comment by vrathee** [comment]
Looks Good.

**Comment by gandhikeyur** [comment]
Reviewed

**Pull request merged**
