### PR TITLE
Code changes for pcm 1270

### PR DESCRIPTION
**Pull request by gandhikeyur**
@renujhamtani @ardasgup Please review

### CODE REVIEW

**Comment by renujhamtani** [comment]
Looks good!

**Comment by ardasgup** [comment]
@gandhikeyur i didn't exactly get the change, it looks you just moved out the span component from its parent one ?

**Comment by gandhikeyur** [comment]
@ardasgup Yes, that was the only change that was needed for the fix. The close button was implemented as a part of the href url, which was creating the issue as clicking on the close button tried to open the attachment in the url.

**Comment by ardasgup** [comment]
Reviewed!

**Pull request merged**
