### PR TITLE
PCM-1981: Added bookmarked account filter

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur Please review.

### CODE REVIEW

**Comment by vrathee** [comment]
Looks Good, Reviewed!

**Comment by gandhikeyur** [comment]
@jtrantin Could you please add the additional dependencies you added in chromed.html to index.html as well.

**Comment by jtrantin** [comment]
@gandhikeyur Done.

**Comment by gandhikeyur** [comment]
Reviewed

**Pull request merged**
