### PR TITLE
PCM-4333 Store the search filter in localStorage

### PR DESCRIPTION
**Pull request by kunyan**
- searchText
- caseGroup
- caseStatus
- bookmarkAccount

All filters can be stored in localStorage

removed unuse code

### CODE REVIEW

**Comment by kunyan** [comment]
@jtrantin pls review

**Comment by kunyan** [comment]
Here is demo link https://projects.engineering.redhat.com/secure/attachment/36383/36383_Filter+with+Refresh.webm

**Comment by jtrantin** [comment]
@renujhamtani This would require some extensive testing, do we merge it now or should we wait for the PCM prod push?

**Comment by jtrantin** [comment]
@kunyan Please fix the conflicts.

**Comment by vrathee** [comment]
@kunyan Also, as part of PCM-4334 ( https://projects.engineering.redhat.com/browse/PCM-4334 ) I added a new filter on case list page.. So we need to make sure it also works post your changes..

**Comment by kunyan** [comment]
@jtrantin @vrathee all conflicts resolved, fix manageAccount  issue, it works now

Please review

**Pull request merged**
