### PR TITLE
PCM-7065: changed get products/version api to hydra

### PR DESCRIPTION
**Pull request by jeudy100**
@rh-kgarg please review

### CODE REVIEW

**Comment by anujsi** [comment]
Did you merge Hydrajs changes?

**Comment by jeudy100** [comment]
@anujsi there weren't any changes needed in hydrajs. All the data just needed to be surfaced on the backend side in the v1 product endpoint.

**Comment by jeudy100** [comment]
@anujsi I found a problem with the strata and hydra properties being different. I mapped the new hydra properties back to the old strata properties, could you review the new changes?

**Comment by anujsi** [comment]
Reviewed.

**Comment by rh-kgarg** [comment]
@jeudy100 Changes look good. Could you also please mention in the jira that we have switched from strata ti hydra for products and version list so that qa can test accordingly

**Pull request merged**
