### PR TITLE
Pcm 851

### PR DESCRIPTION
**Pull request by renujhamtani**
@ardasgup @pbathia Please review and merge. I have added testcases for cases/services to increase the code coverage.

### CODE REVIEW

**Comment by renujhamtani** [comment]
@ardasgup  Wherver the caseService object or any other object is used instead of mockStrataDataService, it was because we needed not to mock strata but to use input values for caseService or any other object.

**Comment by renujhamtani** [comment]
@ardasgup Incorporated ur comment! thanks!

**Comment by ardasgup** [comment]
Reviewed!

**Comment by pbathia** [comment]
Reviewed.

**Pull request merged**
