### PR TITLE
PCM-3837: Adding internal user watchers

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur @engineersamuel Please review.

https://projects.engineering.redhat.com/browse/PCM-3837

Photo with basic description can be found in the jira.

### CODE REVIEW

**Comment by jtrantin** [comment]
Don't merge, found one problem and will do some further changes.

**Comment by jtrantin** [comment]
Done, ready for review & merge.

**Comment by pranvikasha** [comment]
Reviewed!

**Comment by vrathee** [comment]
Reviewed!

**Pull request merged**
