### PR TITLE
PCM-2051: Added angular JS exception handler

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur Please review.

### CODE REVIEW

**Comment by renujhamtani** [comment]
@jtrantin  Is this working on cukes??

**Comment by renujhamtani** [comment]
@jtrantin  as far as i remember, we had removed similar functionality because of some defects*i am not remembering exactly what)..

**Comment by vrathee** [comment]
Reviewed!

**Comment by jtrantin** [comment]
@renujhamtani Tested with Cukes locally and it is working fine. The code that was present in the past was doing something a bit different, it was only re-throwing the errors from angular exception handler to the global exception handler. However, now we are not able to access the globally uncaught JS errors altogether (Watir and cucumber do not allow that now with newest FF), so we need to store the errors locally in the object window.errors, so the automation tests can check and read the errors anytime.

**Comment by renujhamtani** [comment]
Looks good!

**Comment by gandhikeyur** [comment]
Reviewed

**Pull request merged**
